countries = ['korea', 'canada', 'uk', 'china', 'indonesia', 'japan']
print(f"{len(countries)}")
print(f"{countries[0].title()}")
print(f"{countries[3].upper()}")
countries.insert(2, 'iran')
print(countries)
print(f"{len(countries)}")
co_remove = countries.pop(1)
print(f"El pais {co_remove.title()} ha dejado la lista de miembros")
print(countries)
print(f"La lista de miembros ahora es de {len(countries)} paises.")
del countries[-1]
print(countries)
print(f"La lista de miembros ahora es de {len(countries)} paises.")
countries.append('iraq')
print(f"El pais {countries[-1].title()} ha ingresado a la lista de miembros!")
countries.sort()
print(f"Estos son los primeros dos paises ordenados alfabeticamente:\n {countries[0].title()}, {countries[1].title()}")