cars = ['bmw', 'audi', 'toyota', 'subaru']
print("\nHere's the original list:")
print(f"{cars}\n")
print("Here's the sorted list:")
print(f"{sorted(cars)}\n")
print("Here's the original list again:")
print(f"{cars}\n")
print("Here's the reverse sorted list:")
cars.sort(reverse=True)
print(f"{cars}\n")
cars.reverse()
print(cars)
print(len(cars))