places = ['pyongyang', 'sinuiju', 'wonsan', 'kaesong', 'sariwon']
print("Here's the list on original order:")
print(f"{places}\n")
print("Here's the list ordered in alphabetical order:")
print(f"{sorted(places)}\n")
print("Here's the unmodified list with original order:")
print(f"{places}\n")
print("Here's the list in reverse alphabetical order:")
rev_list = sorted(places)
rev_list.reverse()
print(f"{(rev_list)}\n")
print("Here's the unmodified list (again) with original order:")
print(f"{places}\n")
places.reverse()
print("Here's the original list in reverse order")
print(f"{places}\n")
places.reverse()
print("Here's the unmodified list (again) with original order:")
print(f"{places}\n")
print("Here's the list ordered in alphabetical order (cannot be modified):")
places.sort()
print(f"{places}\n")
places.sort(reverse=True)
print("Here's the list ordered in reverse alphabetical order (cannot be modified):")
print(f"{places}\n")