invitados = ['freddie', 'john', 'roger', 'brian']
print(f"Hey {invitados[0].title()}!, I would like to invite you to a dinner tonight, wanna come?")
print(f"Hey {invitados[1].title()}!, I would like to invite you to a dinner tonight, wanna come?")
print(f"Hey {invitados[2].title()}!, I would like to invite you to a dinner tonight, wanna come?")
print(f"Hey {invitados[3].title()}!, I would like to invite you to a dinner tonight, wanna come?")
invitados_remove = invitados.pop(0)
invitados.insert(0, 'adam')
print(f"Sorry guys, but {invitados_remove.title()}, would not come tonight, {invitados[0].title()} would come instead!")
print("\nHey everyone, more friends are coming so we'll move to a bigger table\n")
invitados.insert(0, 'lisa')
invitados.insert(2, 'axel')
invitados.append('david')
print(f"{invitados[0].title()}, has arrived!")
print(f"{invitados[2].title()}, has arrived!")
print(f"{invitados[-1].title()}, has arrived!\n")
print("People are leaving as soon as they finish their dinner...\n")
print(invitados)
print(f"\n{invitados.pop().title()} leave the restaurant :(")
print(f"{invitados.pop().title()} leave the restaurant :(")
print(f"{invitados.pop().title()} leave the restaurant :(")
print(f"{invitados.pop().title()} leave the restaurant :(")
print(f"{invitados.pop().title()} leave the restaurant :(\n")
print(invitados)
del invitados[0]
print(invitados)
del invitados[0]
print(f"\n{invitados}\n")
